version: "3.8"

services:
  postgres-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=localhost
      - POSTGRES_PASSWORD=localhost
      - POSTGRES_DB=localhost
      - POSTGRES_SCHEMA=public
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:z

  redis-kv:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - default
    volumes:
      - ./data/redis:/data/redis

networks:
  default:
    name: le-insight-backend
