version: "3.8"

services:
  postgres-db:
    image: postgres:14-alpine
    env_file:
      - docker.local.env
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis-kv:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - default
    volumes:
      - ./data/redis:/data

networks:
  default:
    name: le-insight-backend
